### ISSUE TITLE
AttributeError: partially initialized module 'voyageai' has no attribute 'Client' (most likely due to a circular import)

### ISSUE THREAD

**Issue by laasya-konidala** [voyage-ai/voyageai-python#10]
I'm working on a Windows laptop, and I'm following the quickstart tutorial. All I've done so far is the pip install and the python -c "import voyageai". After, I pasted the quickstart code (below) and when I tried to run it in my terminal, I get the error that voyageai has no attribute Client. Unlike the quickstart, the Client and .embeddings aren't highlighted in blue text. 

import voyageai
vo = voyageai.Client(api_key="<your-key-here>") # When I ran this, I included my own key, but for debugging purposes I took it out

documents = [
    "The Mediterranean diet emphasizes fish, olive oil, and vegetables, believed to reduce chronic diseases.",
    "Photosynthesis in plants converts light energy into glucose and produces essential oxygen.",
    "20th-century innovations, from radios to smartphones, centered on electronic advancements.",
    "Rivers provide water, irrigation, and habitat for aquatic species, vital for ecosystems.",
    "Apple’s conference call to discuss fourth fiscal quarter results and business updates is scheduled for Thursday, November 2, 2023 at 2:00 p.m. PT / 5:00 p.m. ET.",
    "Shakespeare's works, like 'Hamlet' and 'A Midsummer Night's Dream,' endure in literature."
]

document_embeddings = vo.embed(documents, model="voyage-3", input_type="document").embeddings[0]
print(document_embeddings)

**Comment by fzliu** [comment]
@laasya-konidala Is the name of the file you're running `voyageai.py`? If so, try renaming it e.g. `voyage.py` to something else and run it again.

**Comment by laasya-konidala** [comment]
Thanks! Works now.
