### ISSUE TITLE
The request body is not valid JSON, or some arguments were not specified properly. In particular, Value 'None' supplied for argument 'truncation' is not a valid bool

### ISSUE THREAD

**Issue by carlosatFroom** [voyage-ai/voyageai-python#2]
Changing truncation to False rather than None fixed the issue in client.py 
```
        truncation: Optional[bool] = False, #vs None
```

**Comment by thomas0809** [comment]
Hi,

The `truncation=None` option has been removed and the default has been changed to `True` (see [here](https://github.com/voyage-ai/voyageai-python/blob/e565fb60b854e80ead526a57ea0e6eb1db9efc33/voyageai/client.py#L56)). Please upgrade to our latest version. Sorry about the confusion!
