### ISSUE TITLE
Reranker API

### ISSUE THREAD

**Issue by Amiya-Lahiri-ML** [voyage-ai/voyageai-python#5]
AttributeError                            Traceback (most recent call last)
[<ipython-input-120-2a92b7033a78>](https://localhost:8080/#) in <cell line: 3>()
      1 import voyageai
      2 vo = voyageai.Client(api_key=VOYAGE_API_KEY)
----> 3 reranking = vo.rerank(query, RerankerSummaryList, model="rerank-lite-1", top_k=5)
      4 for r in reranking.results:
      5     print(f"Document: {r.document}")

AttributeError: 'Client' object has no attribute 'rerank'
how to resolve it

**Comment by thomas0809** [comment]
Hi,

Please upgrade to the latest version of the package through `pip install -U voyageai`, and you should be able to use the `rerank` method in `Client`. https://github.com/voyage-ai/voyageai-python/blob/e565fb60b854e80ead526a57ea0e6eb1db9efc33/voyageai/client.py#L81.
