### ISSUE TITLE
Reranker - batch texts

### ISSUE THREAD

**Issue by helloworld53** [voyage-ai/voyageai-python#6]
**Python Client**
How to use batch_texts like in vo.embed to avoid Rate limit  errors per minute ?
 Could you add  that to the docs?
 Thanks

**Comment by thomas0809** [comment]
Hi,

Please see this [guide](https://docs.voyageai.com/docs/rate-limits#how-can-i-avoid-hitting-rate-limits) for suggestions on handling rate limits.
